# Generated by Django 4.1.7 on 2023-03-25 22:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointingPoker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=20, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Pointing Poker',
                'verbose_name_plural': 'Pointing Poker',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=20, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('waiting_participants', 'Aguardando participantes'), ('in_progress', 'Em andamento'), ('closed', 'Finalizado')], default='waiting_participants', max_length=30, verbose_name='Status')),
                ('allow_observers', models.BooleanField(default=True, verbose_name='Permitir observadores?')),
                ('allow_participants_reset_votes', models.BooleanField(default=False, verbose_name='Participantes têm permissão para redefinir votos')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
            },
        ),
        migrations.CreateModel(
            name='SessionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('role', models.CharField(choices=[('observer', 'Observador(a)'), ('owner', 'Dono(a)'), ('player', 'Jogador(a)')], default='observer', max_length=30, verbose_name='Função')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Usuário da Sessão',
                'verbose_name_plural': 'Usuários da Sessão',
            },
        ),
        migrations.CreateModel(
            name='PointValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=10, verbose_name='Descrição')),
                ('value', models.PositiveIntegerField(verbose_name='Valor')),
                ('pointing_poker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pointingpoker', verbose_name='Pointing Poker')),
            ],
            options={
                'verbose_name': 'Valores de pontos',
                'verbose_name_plural': 'Valores de pontos',
                'ordering': ['value'],
            },
        ),
        migrations.AddField(
            model_name='pointingpoker',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session', verbose_name='Sessão'),
        ),
    ]
