# Generated by Django 4.1.7 on 2023-03-27 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_time', models.DurationField(blank=True, null=True, verbose_name='Duração')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Estimativa',
                'verbose_name_plural': 'Estimativas',
            },
        ),
        migrations.CreateModel(
            name='UserEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estimate', verbose_name='Estimativa')),
                ('point_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pointvalue', verbose_name='Pontuação')),
                ('session_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sessionuser', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Estimativa do usuário',
                'verbose_name_plural': 'Estimativas dos usuários',
            },
        ),
    ]
