# Generated by Django 4.1.7 on 2023-03-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estimate_userestimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pontuação'),
        ),
    ]
