# Generated by Django 4.1.7 on 2023-03-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estimate_close_at_estimate_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Dt. Início'),
        ),
    ]
