# Generated by Django 4.1.7 on 2023-03-28 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_estimate_start_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='duration_time',
        ),
    ]
